services:
  car-price-app:
    build: .
    ports:
      - "8050:8050"
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONPATH=/app
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8050 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
